source 'https://cdn.cocoapods.org'
platform :ios, '15.3'

target 'MultiplatformClassifier' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'composeApp', :path => '../composeApp'
  pod 'MediaPipeTasksText'
end
